[package]
name = "chip8"
description = "Cross-platform Chip8 Emulator built in rust"
repository = "https://github.com/JacobMillward/omada_backup"
version = "0.8.0"
authors = ["Jacob Millward <jacob@millward.dev>"]
edition = "2021"

[dependencies]
minifb = "0.23"
rand = "0.8.5"